export const FEES = {
  TRADE_FEE_RATE: 0.05,
  AUCTION_FEE_RATE: 0.07
} as const;

export const STARTING_BALANCE = "1000.00";
export const ANTI_SNIPE_SECONDS = 30;
export const ANTI_SNIPE_MAX_EXTENSIONS = 6;
export const SEALED_BID_WINDOW_SECONDS = 30;
export const OPEN_BID_COOLDOWN_MS = 1500;
export const OPEN_BID_WINDOW_MS = 10_000;
export const OPEN_BID_WINDOW_MAX = 5;
export const SEALED_BID_UPDATE_COOLDOWN_MS = 1000;
export const FAT_FINGER_MULTIPLIER_MARKET = 3;
export const FAT_FINGER_MULTIPLIER_CURRENT = 2;
export const AUCTION_FLAG_LOW_PRICE_RATIO = 0.65;
